# Generated by Django 4.0.1 on 2022-01-26 12:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('tech_stack', models.TextField(blank=True, null=True)),
                ('scoping_due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('sow_pdf', models.URLField(blank=True, null=True)),
                ('call_notes', models.TextField(blank=True, null=True)),
                ('call_date', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True), blank=True, null=True, size=None)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_opportunity', models.BooleanField()),
                ('is_project', models.BooleanField()),
                ('backround_description', models.TextField(blank=True)),
                ('scoping_notes', models.TextField(blank=True)),
                ('sow_review_notes', models.TextField(blank=True)),
                ('resourcing_notes', models.TextField(blank=True)),
                ('company_website_url', models.URLField(blank=True)),
                ('scoping_lead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
                ('weekly_check_ins', models.ManyToManyField(to='employees.WeeklyCheckIn')),
            ],
            options={
                'db_table': 'opportunity',
                'permissions': [('view_only_assigned_opportunities', 'Can view only opportunities to which user is assigned to.')],
            },
        ),
    ]
