# Generated by Django 4.0.1 on 2022-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('opportunities', '0002_alter_opportunity_scoping_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='weekly_check_ins',
            field=models.ManyToManyField(blank=True, to='employees.WeeklyCheckIn'),
        ),
    ]
