# Generated by Django 4.0.1 on 2022-01-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.TextField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('department', models.TextField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_type', models.TextField(blank=True, max_length=100, null=True)),
                ('employee_status', models.TextField(blank=True, max_length=100, null=True)),
                ('reporting_to', models.ForeignKey(blank=True, db_column='reporting_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='WeeklyCheckIn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('week_end_date', models.DateField(blank=True, null=True)),
                ('wellness_survey', models.IntegerField(blank=True, null=True)),
                ('wellness_thoughts', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
            options={
                'db_table': 'weekly_check_in',
            },
        ),
    ]
